services:
  bike_detector_tflite_s:
    image: bike_detector_tflite
    container_name: bike_detector
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      - ./detector:/home/detector/
    devices:
      - '/dev/video0:/dev/video0'
